package com.ecole.models;
// Generated 22 août 2016 14:46:36 by Hibernate Tools 3.4.0.CR1

/**
 * Annee_Scolaire generated by hbm2java
 */
public class Annee_Scolaire implements java.io.Serializable {

	private String code_annee;
	private String designation;

	public Annee_Scolaire() {
	}

	public Annee_Scolaire(String code_annee) {
		this.code_annee = code_annee;
	}

	public Annee_Scolaire(String code_annee, String designation) {
		this.code_annee = code_annee;
		this.designation = designation;
	}

	public String getCode_annee() {
		return this.code_annee;
	}

	public void setCode_annee(String code_annee) {
		this.code_annee = code_annee;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

}
