package com.ecole.models;
// Generated 22 août 2016 14:46:36 by Hibernate Tools 3.4.0.CR1

/**
 * Classe generated by hbm2java
 */
public class Classe  {

	private String code_classe;
	private String designation;
	private String code_niveau;

	public Classe() {
	}

	public Classe(String code_classe) {
		this.code_classe = code_classe;
	}

	public Classe(String code_classe, String designation, String code_niveau) {
		this.code_classe = code_classe;
		this.designation = designation;
		this.code_niveau = code_niveau;
	}

	public String getCode_classe() {
		return this.code_classe;
	}

	public void setCode_classe(String code_classe) {
		this.code_classe = code_classe;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getCode_niveau() {
		return this.code_niveau;
	}

	public void setCode_niveau(String code_niveau) {
		this.code_niveau = code_niveau;
	}

}
