package com.ecole.models;

// default package
// Generated 19 juin 2016 17:12:37 by Hibernate Tools 3.4.0.CR1

/**
 * Compte generated by hbm2java
 */
public class Compte implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1094801825228348945L;
	private String id_utilisateur;
	private String login;
	private String password;
	private String type_compte;

	public Compte() {
	}

	public Compte(String id_utilisateur) {
		this.id_utilisateur = id_utilisateur;
	}

	public Compte(String id_utilisateur, String login, String password, String type_compte) {
		this.id_utilisateur = id_utilisateur;
		this.login = login;
		this.password = password;
		this.type_compte = type_compte;
	}

	public String getId_utilisateur() {
		return this.id_utilisateur;
	}

	public void setId_utilisateur(String id_utilisateur) {
		this.id_utilisateur = id_utilisateur;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getType_compte() {
		return this.type_compte;
	}

	public void setType_compte(String type_compte) {
		this.type_compte = type_compte;
	}

}
