package com.ecole.models;
// Generated 26 juin 2016 11:45:40 by Hibernate Tools 3.5.0.Final

import java.util.Date;


/**
 * Eleve generated by hbm2java
 */
public class Eleve implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID =   8094801111228358969L;
	private String matricule_eleve;
	private String nom;
	private String prenom;
	private Date date_naissance;
	private String sexe;
	private Date deleted;

	public Eleve() {
	}

	public Eleve(String matricule_eleve) {
		this.matricule_eleve = matricule_eleve;
	}

	public Eleve(String matricule_eleve, String nom, String prenom, Date date_naissance, String sexe, Date deleted) {
		this.matricule_eleve = matricule_eleve;
		this.nom = nom;
		this.prenom = prenom;
		this.date_naissance = date_naissance;
		this.sexe = sexe;
		this.deleted = deleted;
	}

	public String getMatricule_eleve() {
		return this.matricule_eleve;
	}

	public void setMatricule_eleve(String matricule_eleve) {
		this.matricule_eleve = matricule_eleve;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public Date getDate_naissance() {
		return this.date_naissance;
	}

	public void setDate_naissance(Date date_naissance) {
		this.date_naissance = date_naissance;
	}

	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	public Date getDeleted() {
		return deleted;
	}

	public void setDeleted(Date deleted) {
		this.deleted = deleted;
	}
	

}
