package com.ecole.models;
// Generated 11 déc. 2016 15:49:12 by Hibernate Tools 3.4.0.CR1

/**
 * Eleve_Classe generated by hbm2java
 */
public class Eleve_Classe implements java.io.Serializable {

	private String matricule_eleve;
	private String code_classe;
	private String code_annee;

	public Eleve_Classe() {
	}

	public Eleve_Classe(String matricule_eleve, String code_classe, String code_annee) {
		this.matricule_eleve = matricule_eleve;
		this.code_classe = code_classe;
		this.code_annee = code_annee;
	}

	public String getMatricule_eleve() {
		return this.matricule_eleve;
	}

	public void setMatricule_eleve(String matricule_eleve) {
		this.matricule_eleve = matricule_eleve;
	}

	public String getCode_classe() {
		return this.code_classe;
	}

	public void setCode_classe(String code_classe) {
		this.code_classe = code_classe;
	}

	public String getCode_annee() {
		return this.code_annee;
	}

	public void setCode_annee(String code_annee) {
		this.code_annee = code_annee;
	}

}
