package com.ecole.models;
// Generated 22 août 2016 14:46:36 by Hibernate Tools 3.4.0.CR1

/**
 * Niveau_Matiere generated by hbm2java
 */
public class Niveau_Matiere implements java.io.Serializable {

	private String code_matiere;
	private String code_niveau;

	public Niveau_Matiere() {
	}

	public Niveau_Matiere(String code_matiere, String code_niveau) {
		this.code_matiere = code_matiere;
		this.code_niveau = code_niveau;
	}

	public String getCode_matiere() {
		return this.code_matiere;
	}

	public void setCode_matiere(String code_matiere) {
		this.code_matiere = code_matiere;
	}

	public String getCode_niveau() {
		return this.code_niveau;
	}

	public void setCode_niveau(String code_niveau) {
		this.code_niveau = code_niveau;
	}

}
