package com.ecole.models;
// Generated 3 juil. 2016 18:47:49 by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur implements java.io.Serializable {
	
	private static final long serialVersionUID =   8094802211228358559L;

	private String id_utilisateur;
	private String nom;
	private String prenom;
	private Date date_naissance;
	private String adresse;
	private String tel;
	private String fonction;
	private String role;
	private String sexe;
	private String cin;

	public Utilisateur() {
	}

	public Utilisateur(String id_utilisateur) {
		this.id_utilisateur = id_utilisateur;
	}

	public Utilisateur(String id_utilisateur, String nom, String prenom, Date date_naissance, String adresse,
			String tel, String fonction, String role, String sexe, String cin) {
		this.id_utilisateur = id_utilisateur;
		this.nom = nom;
		this.prenom = prenom;
		this.date_naissance = date_naissance;
		this.adresse = adresse;
		this.tel = tel;
		this.fonction = fonction;
		this.role = role;
		this.sexe = sexe;
		this.cin = cin;
	}

	public String getId_utilisateur() {
		return this.id_utilisateur;
	}

	public void setId_utilisateur(String id_utilisateur) {
		this.id_utilisateur = id_utilisateur;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public Date getDate_naissance() {
		return this.date_naissance;
	}

	public void setDate_naissance(Date date_naissance) {
		this.date_naissance = date_naissance;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	public String getCin() {
		return this.cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

}
